services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sasa1234
      MYSQL_DATABASE: db_springboot_cloud
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  sonarqube:
    image: sonarqube:10-community   # o la versión LTS que prefieras
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonarqube
      # Si prefieres usar la base interna H2 para pruebas rápidas:
      # SONARQUBE_JDBC_URL: jdbc:h2:tcp://localhost:9092/sonarqube;MODE=PostgreSQL
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/system/health"]
      interval: 15s
      retries: 10
      start_period: 300s
    depends_on:
      - sonarqube_db
    restart: unless-stopped


  sonarqube_db:
    image: postgres:14-alpine
    container_name: sonarqube-db
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  github_runner:
    build:
      context: ./runner
    container_name: github-runner
    env_file:
      - .env
    environment:
      - RUNNER_NAME
      - RUNNER_REPO
      - RUNNER_TOKEN
      - RUNNER_WORKDIR
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # si el runner debe correr contenedores
    depends_on:
      sonarqube:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db_data:
  sonarqube_db_data: