resilience4j:
  circuitbreaker:
    configs:
      mycustomconfig:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 5
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      items:
        base-config: mycustomconfig
  timelimiter:
    configs:
      mycustomconfig:
        timeout-duration: 4s
    instances:
      items:
        base-config: mycustomconfig