spring:
  cloud:
    gateway:
      routes:
      - id: msvc-products
        uri: lb://msvc-products
        predicates:
        - Path=/api/products/**
        # - Header=token, \d+
        # - Method=GET, POST
        # - Query=color
        # - Cookie=color, azul
        # - Header=Content-Type, application/json
        filters:
        - StripPrefix=2
        - CookieExampleFilter=user,Jose,Sample cookie added to response for products
      - id: msvc-items
        uri: lb://msvc-items
        predicates:
        - Path=/api/items/**
        filters:
        - StripPrefix=2
        - AddRequestHeader=token-request, aabbccdd
        - AddResponseHeader=token-response, 1122334455
        - AddRequestParameter=name, Jose
        - SetResponseHeader=Content-Type, text/plain
