name: Multi-module Build & SonarQube Scan (Java 21)

on:
  push:
    branches:
      - master

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: http://sonarqube:9000

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK & Cache Maven
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build & install all modules
        run: |
          mvn clean install -DskipTests -Dsonar.skip=true

  sonar-analysis:
    needs: build
    runs-on: [ self-hosted ]
    strategy:
      matrix:
        module:
          - eureka-server
          - config-server
          - msvc-gateway-server
          - libs-msvc-entities
          - libs-msvc-commons
          - msvc-products
          - msvc-users
          - msvc-items
          - msvc-oauth

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Verify SonarQube connectivity
        continue-on-error: true
        run: |
          curl --fail -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL}/api/server/version"

      - name: SonarQube analysis for ${{ matrix.module }}
        run: |
          mvn -f ${{ matrix.module }}/pom.xml clean verify sonar:sonar \
            -DskipTests=true \
            -Dsonar.login="${SONAR_TOKEN}" \
            -Dsonar.host.url="${SONAR_HOST_URL}" \
            -Dsonar.projectKey="springcloudcourse-${{ matrix.module }}" \
            -Dsonar.projectName="${{ matrix.module }}"
