name: Multi-module Build & SonarQube Scan (Java 21)

on:
  push:
    branches:
      - master

jobs:
  build-and-analyze:
    runs-on: [ self-hosted ]
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug SONAR env vars
        run: |
          echo "🔍 Vars de SONAR en el runner:"
          if env | grep -q SONAR; then
            env | grep SONAR
          else
            echo "  — Ninguna variable SONAR presente"
          fi

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven' # cache de dependencias :contentReference[oaicite:3]{index=3}

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and analyze all modules (debug)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "🔍 Token en Maven: $SONAR_TOKEN"
          mvn clean verify sonar:sonar \
            -X \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.host.url=http://sonarqube:9000 \
            -DskipTests=false
